// AUTO-GENERATED by scripts/gen-tool-index.mjs — DO NOT EDIT
// Run `npm run gen:tools` to refresh.

import { eraseTool, type AnyTool } from "./registry.js";
import {
  clearClipTool,
  wipeCompositionTool,
} from "./clip/clear-clip.js";
import { getClipThumbnailTool } from "./clip/get-thumbnail.js";
import { selectClipTool } from "./clip/select-clip.js";
import {
  setClipPlayDirectionTool,
  setClipPlayModeTool,
  setClipPositionTool,
} from "./clip/transport.js";
import { triggerClipTool } from "./clip/trigger-clip.js";
import { triggerColumnTool } from "./column/trigger-column.js";
import {
  getBeatSnapTool,
  setBeatSnapTool,
} from "./composition/beat-snap.js";
import {
  getCrossfaderTool,
  setCrossfaderTool,
} from "./composition/crossfader.js";
import { getCompositionTool } from "./composition/get-composition.js";
import { selectDeckTool } from "./deck/select-deck.js";
import { addEffectToLayerTool } from "./effect/add-effect.js";
import {
  listLayerEffectsTool,
  listVideoEffectsTool,
} from "./effect/list-effects.js";
import { removeEffectFromLayerTool } from "./effect/remove-effect.js";
import { setEffectParameterTool } from "./effect/set-effect-param.js";
import { clearLayerTool } from "./layer/clear-layer.js";
import {
  listLayerBlendModesTool,
  setLayerBlendModeTool,
} from "./layer/set-blend-mode.js";
import { setLayerBypassTool } from "./layer/set-bypass.js";
import { setLayerOpacityTool } from "./layer/set-opacity.js";
import {
  listLayerTransitionBlendModesTool,
  setLayerTransitionBlendModeTool,
  setLayerTransitionDurationTool,
} from "./layer/transition.js";
import { oscQueryTool } from "./osc/query.js";
import { oscSendTool } from "./osc/send.js";
import { oscStatusTool } from "./osc/status.js";
import { oscSubscribeTool } from "./osc/subscribe.js";
import { cacheRefreshTool } from "./store/cache-refresh.js";
import { cacheStatusTool } from "./store/cache-status.js";
import { getTempoTool } from "./tempo/get-tempo.js";
import { resyncTempoTool } from "./tempo/resync-tempo.js";
import { setBpmTool } from "./tempo/set-bpm.js";
import { tapTempoTool } from "./tempo/tap-tempo.js";

export const allTools: ReadonlyArray<AnyTool> = [
  eraseTool(clearClipTool),
  eraseTool(wipeCompositionTool),
  eraseTool(getClipThumbnailTool),
  eraseTool(selectClipTool),
  eraseTool(setClipPlayDirectionTool),
  eraseTool(setClipPlayModeTool),
  eraseTool(setClipPositionTool),
  eraseTool(triggerClipTool),
  eraseTool(triggerColumnTool),
  eraseTool(getBeatSnapTool),
  eraseTool(setBeatSnapTool),
  eraseTool(getCrossfaderTool),
  eraseTool(setCrossfaderTool),
  eraseTool(getCompositionTool),
  eraseTool(selectDeckTool),
  eraseTool(addEffectToLayerTool),
  eraseTool(listVideoEffectsTool),
  eraseTool(listLayerEffectsTool),
  eraseTool(removeEffectFromLayerTool),
  eraseTool(setEffectParameterTool),
  eraseTool(clearLayerTool),
  eraseTool(setLayerBlendModeTool),
  eraseTool(listLayerBlendModesTool),
  eraseTool(setLayerBypassTool),
  eraseTool(setLayerOpacityTool),
  eraseTool(setLayerTransitionDurationTool),
  eraseTool(listLayerTransitionBlendModesTool),
  eraseTool(setLayerTransitionBlendModeTool),
  eraseTool(oscQueryTool),
  eraseTool(oscSendTool),
  eraseTool(oscStatusTool),
  eraseTool(oscSubscribeTool),
  eraseTool(cacheRefreshTool),
  eraseTool(cacheStatusTool),
  eraseTool(getTempoTool),
  eraseTool(resyncTempoTool),
  eraseTool(setBpmTool),
  eraseTool(tapTempoTool),
];
